# Playbook for configuring client1

- name: Set up client1 VM
  hosts: client1
  vars:
    home: "{{ ansible_facts['user_dir'] }}"
    asset_dir: "{{ home }}/mahiru/assets"
    script_dir: "{{ home }}/mahiru/scripts"
    certs_dir: "{{ home }}/mahiru/certs"
    private_dir: "{{ home }}/mahiru/private"

  tasks:
  - name: Create assets directory
    file:
      path: "{{ asset_dir }}"
      state: directory

  - name: Copy assets
    synchronize:
      src: "../../build/images/{{ item }}"
      dest: "{{ asset_dir }}/{{ item }}"
    loop:
      - data-asset-base.tar.gz
      - compute-asset.tar.gz

  - name: Create private dir
    file:
      path: "{{ private_dir }}"
      state: directory
      mode: 0700

  - name: Copy keys
    synchronize:
      src: "../../build/certs/site1/private/party1_main_key.pem"
      dest: "{{ private_dir }}/party1_main_key.pem"

  - name: Create certs dir
    file:
      path: "{{ home }}/mahiru/certs"
      state: directory

  - name: Copy certs
    synchronize:
      src: "../../build/certs/{{ item.src }}"
      dest: "{{ certs_dir }}/{{ item.dest }}"
    loop:
      - src: site1/certs/party1_main_cert.pem
        dest: party1_main_cert.pem
      - src: site1/certs/party1_user_ca_cert.pem
        dest: party1_user_ca_cert.pem
      - src: site1/certs/site1_https_cert.pem
        dest: site1_https_cert.pem

  - name: Create script directory
    file:
      path: "{{ script_dir }}"
      state: directory

  - name: Copy scripts
    synchronize:
      src: "client1/{{ item }}"
      dest: "{{ script_dir }}/{{ item }}"
    loop:
      - init_site.py
      - submit_job.py

  - name: Initialise local site
    command:
      cmd: "python3 {{ script_dir }}/init_site.py"


- name: Set up client2 VM
  hosts: client2
  vars:
    home: "{{ ansible_facts['user_dir'] }}"
    asset_dir: "{{ home }}/mahiru/assets"
    script_dir: "{{ home }}/mahiru/scripts"
    certs_dir: "{{ home }}/mahiru/certs"
    private_dir: "{{ home }}/mahiru/private"

  tasks:
  - name: Create assets dir
    file:
      path: "{{ asset_dir }}"
      state: directory

  - name: Copy assets
    synchronize:
      src: ../../build/images/data-asset-input.tar.gz
      dest: "{{ asset_dir }}/data-asset-input.tar.gz"

  - name: Create private dir
    file:
      path: "{{ private_dir }}"
      state: directory
      mode: 0700

  - name: Copy keys
    synchronize:
      src: "../../build/certs/site2/private/party2_main_key.pem"
      dest: "{{ private_dir }}/party2_main_key.pem"

  - name: Create certs dir
    file:
      path: "{{ home }}/mahiru/certs"
      state: directory

  - name: Copy certs
    synchronize:
      src: "../../build/certs/{{ item.src }}"
      dest: "{{ certs_dir }}/{{ item.dest }}"
    loop:
      - src: site2/certs/party2_main_cert.pem
        dest: party2_main_cert.pem
      - src: site2/certs/party2_user_ca_cert.pem
        dest: party2_user_ca_cert.pem
      - src: site2/certs/site2_https_cert.pem
        dest: site2_https_cert.pem

  - name: Create script directory
    file:
      path: "{{ script_dir }}"
      state: directory

  - name: Copy init script
    synchronize:
      src: client2/init_site.py
      dest: "{{ script_dir }}/init_site.py"

  - name: Initialise local site
    command:
      cmd: "python3 {{ script_dir }}/init_site.py"
