openapi: "3.0.0"
info:
  version: 0.1.0
  title: Proof of concept Asset Store
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: /
paths:
  /assets:
    post:
      summary: Store an asset
      operationId: proof_of_concept.asset_store_server.controllers.assets_controller.store_asset
      tags:
        - assets
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Asset'
      responses:
        '201':
          description: Null response

    get:
      summary: Retrieve an asset by ID
      operationId: proof_of_concept.asset_store_server.controllers.assets_controller.get_asset
      tags:
        - assets
      parameters:
        - name: asset_id
          in: query
          required: true
          description: "The id of the asset to retrieve"
          example: "1"
          schema:
            type: string
        - name: requester
          in: query
          required: true
          description: "The id of the requester"
          example: "Party1"
          schema:
            type: string
      responses:
        '200':
          description: The asset
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Asset"

components:
  schemas:
    Asset:
      description: "A representation of a computation or piece of data."
      type: object
      required:
        - id
      properties:
        id:
          description: "ID of the asset"
          type: string
          example: "id:party1_ns/collection/asset1"
        data:
          description: "Data related to the asset"
          example: 42
        metadata:
          $ref: "#/components/schemas/Metadata"

    Metadata:
      description: "Metadata of the asset"
      type: object
      required:
        - job
        - item
      properties:
        job:
          $ref: "#/components/schemas/Job"
        item:
          description: "The item in the job's workflow corresponding to this asset."
          example: "item_1"
          type: string

    Job:
      description: "A minimal job that will generate this asset."
      type: object
      required:
        - workflow
        - inputs
      properties:
        workflow:
          $ref: "#/components/schemas/Workflow"
        inputs:
          description: "A dictionary mapping the workflow's input
                        parameters to data set ids."
          example:
            "x1": "id:party1_ns/collection/input1"
            "x2": "id:party1_ns/collection/input2"
          type: object
          additionalProperties:
            type: string

    Workflow:
      required:
        - inputs
        - outputs
        - steps
      properties:
        inputs:
          description: "A list of input variables"
          example: ['x1', 'x2']
          type: array
          items:
            type: string
        outputs:
          description: "Dict mapping output parameter names to
                        corresponding step outputs of the form step.output."
          example:
            "y1": "id:party1_ns/collection/y1"
          type: object
          additionalProperties:
            type: string
        steps:
          type: array
          items:
            $ref: "#/components/schemas/WorkflowStep"

    WorkflowStep:
      required:
        - name
        - inputs
        - outputs
        - compute_asset_id
      properties:
        name:
          example: "compute_something"
          type: string
        inputs:
          description: "Dict mapping input parameter names to references to
                        their sources, either the name of a workflow input,
                        or of the form other_step.output_name."
          example:
            "x1": "id:party1_ns/collection/input1"
            "x2": "id:party1_ns/collection/input2"
          type: object
          additionalProperties:
            type: string
        outputs:
          description: "List of names of outputs produced"
          type: array
          items:
            example: "id:party1_ns/collection/result1"
            type: string
        compute_asset_id:
          example: "id:party1_ns/collection/asset1"
          type: string
