# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from proof_of_concept.asset_store_server.models.base_model_ import Model
from proof_of_concept.asset_store_server.models.metadata import Metadata
from proof_of_concept import util


class Asset(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, data: object=None, metadata: Metadata=None):  # noqa: E501
        """Asset - a model defined in Swagger

        :param id: The id of this Asset.  # noqa: E501
        :type id: str
        :param data: The data of this Asset.  # noqa: E501
        :type data: object
        :param metadata: The metadata of this Asset.  # noqa: E501
        :type metadata: Metadata
        """
        self.swagger_types = {
            'id': str,
            'data': object,
            'metadata': Metadata
        }

        self.attribute_map = {
            'id': 'id',
            'data': 'data',
            'metadata': 'metadata'
        }
        self._id = id
        self._data = data
        self._metadata = metadata

    @classmethod
    def from_dict(cls, dikt) -> 'Asset':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Asset of this Asset.  # noqa: E501
        :rtype: Asset
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Asset.


        :return: The id of this Asset.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Asset.


        :param id: The id of this Asset.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def data(self) -> object:
        """Gets the data of this Asset.


        :return: The data of this Asset.
        :rtype: object
        """
        return self._data

    @data.setter
    def data(self, data: object):
        """Sets the data of this Asset.


        :param data: The data of this Asset.
        :type data: object
        """
        if data is None:
            raise ValueError("Invalid value for `data`, must not be `None`")  # noqa: E501

        self._data = data

    @property
    def metadata(self) -> Metadata:
        """Gets the metadata of this Asset.


        :return: The metadata of this Asset.
        :rtype: Metadata
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Metadata):
        """Sets the metadata of this Asset.


        :param metadata: The metadata of this Asset.
        :type metadata: Metadata
        """

        self._metadata = metadata
